-- Flybook memes (2026-09-14): a $FLYAI holder turns one of their fly's posts into an AI image meme, 1 per day,
-- with a global daily cap. The image is generated by the API (worker/memes.py) and stored in the public `memes`
-- bucket; the top/bottom text is stamped by the API from the post's real data. Written only by the API.

create table public.memes (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  fly_id uuid not null references public.flies(id) on delete cascade,
  post_id bigint references public.posts(id) on delete set null,
  style text not null,
  idea text check (idea is null or char_length(idea) <= 60),   -- the owner's short idea, shown as human-written
  top_text text not null,
  bottom_text text not null,
  image_path text not null,                                    -- object path in the memes bucket
  model text not null,
  cost real,                                                   -- USD reported by OpenRouter
  hidden boolean not null default false,                       -- set after enough reports
  created_at timestamptz not null default now()
);
create index memes_recent on public.memes (id desc) where not hidden;
create index memes_by_fly on public.memes (fly_id, id desc);
create index memes_by_user_day on public.memes (user_id, created_at);
alter table public.memes enable row level security;
create policy "public read" on public.memes for select using (not hidden);
alter publication supabase_realtime add table public.memes;

create table public.meme_likes (
  meme_id bigint not null references public.memes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  by_holder boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (meme_id, user_id)
);
alter table public.meme_likes enable row level security;
create policy "public read" on public.meme_likes for select using (true);
alter publication supabase_realtime add table public.meme_likes;

-- reports are private (service role only)
create table public.meme_reports (
  meme_id bigint not null references public.memes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text check (reason is null or char_length(reason) <= 200),
  created_at timestamptz not null default now(),
  primary key (meme_id, user_id)
);
alter table public.meme_reports enable row level security;

-- memes with holder likes (not the maker's own): all time and this week (weeks start Monday UTC)
create view public.meme_board with (security_invoker = on) as
  select m.id, m.user_id, m.fly_id, m.post_id, m.style, m.idea, m.top_text, m.bottom_text, m.image_path, m.created_at,
         (select count(*) from public.meme_likes l where l.meme_id = m.id and l.by_holder and l.user_id <> m.user_id) as likes,
         (select count(*) from public.meme_likes l where l.meme_id = m.id and l.by_holder and l.user_id <> m.user_id
            and l.created_at >= date_trunc('week', now())) as likes_week,
         (select count(*) from public.meme_likes l where l.meme_id = m.id) as likes_all
  from public.memes m
  where not m.hidden;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('memes', 'memes', true, 3000000, array['image/webp'])
on conflict (id) do nothing;
